CC = gcc
CFLAGS = -O2 -Wall -Wextra -MMD -MP
LDFLAGS = -lpthread -lm

# Everything the build produces goes under build/ (objects, their .d files, the test and bench
# binaries), except the program itself, which stays at the top as ./desktop_search.
BUILD = build

OBJS = $(addprefix $(BUILD)/, main.o run.o ctx.o path.o utf8.o search.o reply.o bsl.o snapshot.o tui.o \
	threadpool.o pagerank.o token_index.o watch.o scan.o server.o client.o)
TARGET = desktop_search

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

$(BUILD)/%.o: %.c | $(BUILD)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD) $(BUILD)/tests:
	mkdir -p $@

# Header dependencies generated by -MMD (written next to each object), so that a struct change in a
# header rebuilds every object that includes it. Without this, objects built against different
# layouts get linked together.
-include $(OBJS:.o=.d)

# Tests: each binary links only the modules it exercises. test_e2e.py drives the real program.
# No -MMD here: test sources are single files, and their .d files are not worth tracking.
TEST_CFLAGS = -O2 -Wall -Wextra -I.
T = $(BUILD)/tests
TESTS = $(addprefix $(T)/, test_htable test_bsl_seek test_token test_ctx test_inject test_reply test_pagerank \
	test_snapshot)

$(T)/test_htable: tests/test_htable.c htable.h list.h | $(T)
	$(CC) $(TEST_CFLAGS) -o $@ $<

$(T)/test_bsl_seek: tests/test_bsl_seek.c $(BUILD)/bsl.o | $(T)
	$(CC) $(TEST_CFLAGS) -o $@ $^

$(T)/test_token: tests/test_token.c $(BUILD)/token_index.o $(BUILD)/bsl.o | $(T)
	$(CC) $(TEST_CFLAGS) -o $@ $^

# Everything but main, run, event, tui and client: what a test of the index side links against.
CORE_OBJS = $(addprefix $(BUILD)/, ctx.o path.o utf8.o search.o reply.o bsl.o snapshot.o pagerank.o threadpool.o \
	token_index.o watch.o scan.o server.o)

$(T)/test_ctx: tests/test_ctx.c $(CORE_OBJS) | $(T)
	$(CC) $(TEST_CFLAGS) -o $@ $^ $(LDFLAGS)

# scan.c and tui.c are included as source, so scan.o is left out.
$(T)/test_inject: tests/test_inject.c scan.c tui.c $(filter-out $(BUILD)/scan.o,$(CORE_OBJS)) | $(T)
	$(CC) $(TEST_CFLAGS) -Wno-unused-result -Wl,--wrap=calloc -o $@ $< $(filter-out $(BUILD)/scan.o,$(CORE_OBJS)) $(LDFLAGS)

$(T)/test_reply: tests/test_reply.c $(CORE_OBJS) | $(T)
	$(CC) $(TEST_CFLAGS) -o $@ $^ $(LDFLAGS)

$(T)/test_pagerank: tests/test_pagerank.c $(BUILD)/pagerank.o $(BUILD)/threadpool.o | $(T)
	$(CC) $(TEST_CFLAGS) -o $@ $^ $(LDFLAGS)

$(T)/test_snapshot: tests/test_snapshot.c $(CORE_OBJS) | $(T)
	$(CC) $(TEST_CFLAGS) -o $@ $^ $(LDFLAGS)

test: $(TARGET) $(TESTS)
	@for t in $(TESTS); do echo "== $$t"; ./$$t || exit 1; done
	@echo "== tests/test_query.py"; python3 tests/test_query.py ./$(TARGET)
	@echo "== tests/test_daemon.py"; python3 tests/test_daemon.py ./$(TARGET)
	@echo "== tests/test_e2e.py"; python3 tests/test_e2e.py ./$(TARGET)

# Benchmarks: timing only, not run by `make test`.
BENCHES = $(T)/bench_pagerank

$(T)/bench_pagerank: tests/bench_pagerank.c $(BUILD)/pagerank.o $(BUILD)/threadpool.o | $(T)
	$(CC) $(TEST_CFLAGS) -o $@ $^ $(LDFLAGS)

bench: $(BENCHES)
	@for shape in "200000 20000" "500000 50000" "200000 2000000" "50000 1000000"; do \
		./$(T)/bench_pagerank $$shape; done

clean:
	rm -rf $(BUILD) $(TARGET)

.PHONY: all test bench clean
